[package]
name = "enumdoc_derive"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.108", features = ["extra-traits"] }
proc-macro2 = "1.0.103"
quote = "1.0"
